var recommendations = new Object();
recommendations['1'] = ['Web Development Immersive – General Assembly', 'Certificate – Nova Scotia Community College', 'Bachelor of Science in Computer Science – University of California', 'Computer Science – University of Maryland', 'Certificate – British Columbia Institute of Technology', 'Bachelor of Science in Computer Science – California State University', 'Bachelor of Science in Computer Science – Middlesex University', 'Bachelor of Science in Computer Science – Politecnico di Milano', 'Bachelor of Technology – Jawaharlal Nehru Technological University', 'Full Stack Web Development – App Academy']
recommendations['2'] = ['Online Course – Codecademy', 'Master of Computer Applications – Anna University', 'Bachelor of Science in Computer Science – University of California', 'Master of Computer Applications – Sikkim Manipal University', 'Bachelor Information Technology – Macquarie University', 'Bachelor of Science in Computer Science – University of Karachi', 'Bachelor of Technology– Anna University', 'Bachelor of Engineering in Computer Science and Engineering – Anna University', 'Bachelor of Computer Applications – Guru Gobind Singh Indraprastha University', 'Course – University of Buenos Aires']
recommendations['3'] = ['Certificate – British Columbia Institute of Technology', 'Bachelor of Science in Computer Science – University of California', 'Course – University of Buenos Aires', 'Computer Information Systems – Devry University', 'Master of Science – Birla Institute', 'Bachelor of Engineering – Anna University']
recommendations['4'] = ['Certificate – Madison College', 'Computer Science – Rochester Institute of Technology', 'Certificate – Nova Scotia Community College', 'Master of Science – Birla Institute', 'Online Course – Mongodb University', 'Web Development – Dev Bootcamp', 'Bachelor of Science in Computer Science – Florida State University', 'Web Development Immersive – General Assembly', 'Bachelor of Science in Computer Science – University of Michigan', 'Bachelor of Science in Computer Science – University of Havana']
recommendations['5'] = ['Web Development Immersive – General Assembly', 'Certificate – Nova Scotia Community College', 'Certificate – British Columbia Institute of Technology', 'Bachelor of Science in Computer Science – University of Michigan', 'Bachelor in Computer Science – Central University', 'Computer Science – University of Havana', 'Bachelor of Science in Computer Science – Middlesex University', 'Online course – Mongodb University', 'Certificate – Notre Dame University', 'Online course – Microsoft']
recommendations['6'] = ['Certificate – Nova Scotia Community College', 'Bachelor of Technology – Jawaharlal Nehru Technological University', 'Master of Science in Software Engineering – San Jose State University', 'Bachelor of Science in Computer Science – University of California', 'Master of Science in Computer Science – Maharishi University of Management', 'Bachelor of Science in Computer Science – University of the Philippines.Bachelor of Science in Computer Science – University of Michigan', 'Web Development Immersive – General Assembly', 'Bachelor of Science in Computer Science – University of Bucharest', 'Bachelor in Computer Science – Central University']
recommendations['8'] = ['Bachelor of Science in Computer Science – Central University', 'Bachelor of Science in Computer Science – University of California', 'Certificate – Nova Scotia Community College', 'Web Development Immersive – General Assembly', 'Computer Science – University of Texas', 'Master of Computer Applications – Anna University', 'Master Computer Science – Maharishi University of Management', 'Certificate – Code Camp', 'Certificate – Stanford University', 'Bachelor of Information Technology – Macquarie University']
recommendations['9'] = ['Bachelor of Science in Computer Science – University of the Philippines', 'Certificate – Nova Scotia Community College', 'Web Development Immersive – General Assembly', 'Bachelor of Science in Information Technology – Rochester Institute of Technology', 'Bachelor of Science in Computer Science – University of California', 'Bachelor of Science in Computer Science – University of Michigan', 'Bachelor of Science in Computer Science – University of Havana', 'Bachelor of Science in Computer Science – Central University', 'Bachelor of Science in Computer Science – Middlesex University', 'Certificate – Stanford University']
recommendations['10'] = ['Bachelor of Science in Computer Science – University of Wisconsin', 'Master of Science in Computer Science – University of Southern California', 'Bachelor of Science in Computer Science – University of the Philippines', 'Bachelor of Science in Computer Science – University of California', 'Bachelor of Science in Computer Science – University of Illinois', 'Master of Science in Computer Science – University of Illinois']
recommendations['11'] = ['Master of Science Computer Science – Georgia Institute of Technology', 'Bachelor of Science in Computer Science – University of California', 'Bachelor of Science in Computer Science – University of Bucharest', 'Bachelor of Engineering – Gujarat Technological University', 'Bachelor of Science in Computer Science – University of Michigan', 'Bachelor of Science in Computer Science – Brigham Young', 'Bachelor of Science in Computer Science – University of the Philippines', 'Bachelor of Science in Computer Science – Florida State', 'Bachelor of Technology – National Institute', 'Bachelor of Science in Computer Science – University of Havana']
recommendations['12'] = ['Online Course – Mongodb University', 'Certificate – Nova Scotia Community College', 'Bachelor of Science in Computer Science – California State University', 'Bachelor of Science in Computer Science – University of California', 'Bachelor of Science in Computer Science – University of Wisconsin', 'Bachelor of Science in Computer Science and engineering – Bangladesh University', 'Bachelor of Science in Computer Science – Oregon State University', 'Computer Science – University of Texas', 'Bachelor of Science in Computer Science – Brigham Young University', 'Computer Science – Rochester Institute of Technology']
recommendations['16'] = ['Master of Science Computer Science - Maharishi University of Management', 'Certificate - Nova Scotia Community College', 'Bachelor of Science in Computer Science - University of Texas', 'Master of Science Computer Science - University of Illinois', 'Bachelor of Science in Computer Science - Central University', 'Bachelor of Science in Computer Science - University of California', 'Bachelor of Science in Computer Science - University of Michigan', 'Bachelor in Computer Science - Central University', 'Bachelor of Science in Computer Science - University of Bucharest', 'Bachelor in Computer Science - Universita Degli Studi di Padova']
recommendations['17'] = ['Online Course - Mongodb University', 'Bachelor of Science in Computer Science - Central University', 'Master of Science Computer Science - University of Illinois', 'Bachelor of Science in Computer Science - Florida State University', 'Master of Science in Software Engineering - San Jose State University', 'Bachelor of Science in Computer Science - University of California', 'Bachelor of Science in Information Technology - Rochester Institute of Technology', 'Computer Science - University of Texas', 'Bachelor of Science in Computer Science - University of Bucharest', 'Computer Science - Rochester Institute of Technology']
recommendations['18'] = ['Bachelor of Science in Computer Science - Georgia Institute of Technology', 'Master in Computer Science - University of Illinois', 'Bachelor of Engineering- University of Mumbai', 'Master of Science Computer Science - University of California', 'Bachelor of Science in Computer Science - University of California', 'Master of Science Computer Science - New York University', 'Bachelor of Engineering - University of Mumbai', 'Bachelor of Engineering in Computer Science - Birla Institute of Technology', 'Master of Science Computer Science - Georgia Institute of Technology']
recommendations['24'] = ['Web Development Immersive - General Assembly', 'Computer Science - University of California', 'Full Stack Web Development - Code Camp', 'Bachelor of Science in Computer Science - University of Minnesota', 'Online Course - Codecademy', 'Certificate - Code Camp', 'Bachelor of Science Interactive Multimedia Design - University of Ulster']
recommendations['27'] = ['Master of Science Computer Science - Georgia Institute of Technology', 'Bachelor of Science in Computer Science - University of Maryland', 'Bachelor of Science in Computer Science - University of Warsaw', 'Bachelor of Science in Computer Science - Brigham Young University', 'Bachelor of Science in Computer Science - University of Massachusetts', 'Computer Science - Technical University', 'Bachelor of Science in Computer Science - University of California', 'Bachelor of Science in Computer Science - Georgia Institute of Technology']
recommendations['28'] = ['Bachelor of Engineering in Computer Engineering - Mumbai University', 'Bachelor of Engineering - Anna University', 'Bachelor of Science in Computer Science - University of Michigan', 'Bachelor of Science in Computer Science - University of the Philippines', 'Master of Science Computer Science - Georgia Institute of Technology', 'Master of Science - University of California']
recommendations['29'] = ['Bachelor of Engineering in Computer Engineering - Mumbai University', 'Master of Science Computer Science - University of Florida', 'Bachelor Technology - Indian Institute of Technology', 'Master Computer Science - Technical University', 'Master of Science Computer Science - New York University', 'Master of Science Software Engineering - San Jose State University', 'Bachelor of Science in Computer Science - University of Maryland', 'Master of Science Computer Science - University of California', 'Bachelor of Technology in Computer Engineering - Nirma University', 'Bachelor of Science in Computer Science - University of Sao Paulo']
recommendations['30'] = ['Bachelor of Science in Computer Science - University of Sao Paulo', 'Software Engineering - Hack Reactor', 'Bachelor of Science in Computer Science - University of California', 'Master of Science Computer Science - Georgia Institute of Technology', 'Master of Science Computer Science - University of California', 'Bachelor Technology - National Institute', 'Bachelor of Science in Computer Science - University of the Philippines', 'Online Course - Mongodb University', 'Certificate - Nova Scotia Community College', 'Bachelor - University of California']
recommendations['31'] = ['Bachelor of Science in Computer Science - University of the Philippines', 'Certificate - Nova Scotia Community College', 'Bachelor of Science in Computer Science - California State University', 'Bachelor of Science in Computer Science - University of Texas', 'Master of Science Computer Science - University of Illinois', 'Web Development - Coding Dojo', 'Master of Science Computer Science - Maharishi University of Management', 'Bachelor Computer Science - Central University', 'Bachelor of Science in Computer Science - University of Michigan', 'Bachelor of Science in Computer Science - Universidade Catolica']
recommendations['33'] = ['Bachelor of Technology - National Institute', 'Master of Science Computer Science - Georgia Institute of Technology', 'Bachelor Technology - National Institute', 'Bachelor of Science in Computer Science - University of Illinois', 'Bachelor of Science in Computer Science - University of California', 'Bachelor of Engineering - Visvesvaraya TechnologicalUniversity', 'Bachelor of Science in Computer Science - University of Bucharest', 'Master of Science Computer Science - Epitech', 'Bachelor of Science in Computer Science - Georgia Institute of Technology', 'Computer Science - University of California']
recommendations['34'] = ['Bachelor of Science in Computer Science - University of California', 'Online Course - Mongodb University', 'Certificate - Nova Scotia Community College', 'Web Development - Coding Dojo', 'Web Development Immersive - General Assembly', 'Bachelor of Technology - West Bengal University of Technology', 'Mastery Certificate - University of California', 'Berkeley', 'Certificate - British Columbia Institute of Technology', 'Bachelor of Engineering - Anna University', 'Bachelor of Arts- University of California']
recommendations['35'] = ['Certificate - British Columbia Institute of Technology', 'Bachelor of Technology- Anna University', 'Master of Computer Applications - Anna University', 'Bachelor of Technology in Computer Science - Kerala University', 'Bachelor of Computer Applications - Ignou']
recommendations['38'] = ['Bachelor of Science in Computer Science - Warsaw University', 'Certificate - South Pacific Sil', 'Bachelor of Science in Computer Science - University of California', 'Computer Science - Arizona State University', 'Bachelor of Science in Computer Science - Technical University', 'Master of Business Administration in Information Systems - American University', 'Bachelor of Science in Computer Science - Belarusian State University University', 'Bachelor of Science in Computer Science - University of Havana', 'Bachelor of Science in Computer Science - University of the Punjab', 'Bachelor of Science in Computer Science - University of Applied Science']
recommendations['39'] = ['Bachelor of Science in Computer Science - University of California', 'Bachelor of Science in Computer Science - University of Massachusetts', 'Bachelor of Science in Computer Science - University of Texas', 'Bachelor of Science in Computer Science - University of Texas', 'Computer Science - Rochester Institute of Technology', 'Bachelor of Science in Computer Science - California State University', 'Computer Science - University of Maryland', 'Bachelor of Science in Computer Science - Arizona State University', 'Bachelor of Science in Computer Science - University of Warsaw', 'Bachelor of Science - University of Illinois']
recommendations['42'] = ['Bachelor of Science in Computer Science - University of California', 'Bachelor of Science in Computer Science - Virtual University', 'Master of Computer Applications - Anna University', 'Master of Science in Information Technology - Punjab Technical University', 'Bachelor of Technology in Information Technology - Anna University', 'Master in Computer Applications - Sikkim Manipal', 'Bachelor of Engineering in Computer Science - Anna University', 'Master in Computer Applications - Gujarat Technological University']
recommendations['43'] = ['Bachelor of Science in Computer Science - Warsaw University', 'Bachelor of Science in Computer Science - University of California', 'Master of Science in Computer Science - University of Washington', 'Master of Business Administration in Management Information Systems - American University', 'Bachelor information Technology - Queensland University of Technology', 'Bachelor of Science in Computer Science - Technical University', 'Bachelor of Science - Universidade de Coimbra', 'Bachelor of Science in Computer Science - University of Nebraska', 'Bachelor of Science in Computer Science - University of Applied Science', 'Bachelor of Science in Computer Science - University of Havana']
recommendations['45'] = ['Bachelor of Science in Computer Science - Warsaw University', 'Bachelor of Science in Computer Science - University of California', 'Certificate - South Pacific Sil', 'Bachelor engineering - Anna University', 'Bachelor of Science in Computer Science - Technical University']
recommendations['48'] = ['Bachelor of Engineering in Computer Science and engineering - Anna University', 'Master - National Technical University of Ukraine', 'Bachelor of Science in Computer Science - University of Illinois', 'Bachelor of Science in Computer Science - Indiana University', 'Certificate - British Columbia Institute of Technology', 'Bachelor of Science in Computer Science - University of Karachi', 'Bachelor of Science in Computer Science - University of California']
recommendations['62'] = ['Web Development Immersive - General Assembly', 'Web Development - Dev Bootcamp', 'Web Development - App Academy', 'Full Stack Web Development - App Academy', 'Web Development - General Assembly', 'Web Development - Makers Academy', 'Computer Science - University of Maryland', 'Bachelor of Science in Computer Science - University of California', 'Bachelor of Science in Computer Science - University of North Carolina', 'Certificate - Madison College']
recommendations['63'] = ['Bachelor of Science in Computer Science - University of California', 'Bachelor of Science in Computer Science - Warsaw University', 'Bachelor of Science in Computer Science - National University of Computer and Emerging Sciences', 'Video Game Design and Development - Trios College', 'Bachelor of Science in Computer Science - State University', 'Bachelor of Science in Computer Science - Universidad Complutense de Madrid']
recommendations['65'] = ['Bachelor Technology - Jawaharlal Nehru Technological University', 'Certificate - Nova Scotia Community College', 'Bachelor engineering - Visvesvaraya Technological University', 'Master of Computer Applications - Sikkim Manipal', 'Bachelor engineering - Anna University', 'Master computer application - Gujarat Technological University', 'Bachelor of Science in Computer Science - University of Maryland', 'Bachelor of Science in Computer Science - University of California', 'Computer Science - Indiana University', 'Master Computer Applications - Anna University']
recommendations['67'] = ['Bachelor of Science in Computer Science - Warsaw University', 'Certificate - South Pacific Sil', 'Bachelor of Science in Computer Science - University of California', 'Bachelor of Science in Computer Science - Technical University', 'Software Engineering - Niit', 'Bachelor of Science in Computer Science - Belarusian State University University', 'Bachelor of Science in Computer Science - University of Havana', 'Bachelor of Science in Computer Science - University of Bucharest', 'Bachelor of Science in Computer Science - Georgia State University', 'Bachelor engineering - Anna University']
recommendations['85'] = ['Master of Science - University of California', 'Computer Science - University of California', 'Bachelor of Science in Computer Science - University of Michigan', 'Bachelor of Science in Computer Science - University of California', 'Bachelor of Science in Computer Science - University of Texas', 'Master of Science in Computer Science - University of Texas', 'Bachelor Technology - Indian Institute of Technology', 'Bachelor of Science in Computer Science - Brigham Young University', 'Bachelor - University of California', 'Computer Science - University of Maryland']
recommendations['86'] = ['Bachelor of Science in Computer Science - University of Illinois', 'Master of Science in Computer Science - Johns Hopkins University', 'Bachelor engineering - Anna University', 'Bachelor of Science in Computer Science - Worcester Polytechnic Institute', 'Bachelor of Science in Computer Science - University of California', 'Bachelor Technology - Indian Institute of Technology', 'Bachelor of Science in Computer Science - Brigham Young University', 'Bachelor of Science in Computer Science - California State University', 'Computer Science - Technical University', 'Bachelor of Science in Computer Science - University of Massachusetts']
recommendations['87'] = ['Bachelor of Science in Computer Science - Washington State University', 'Bachelor of Science in Computer Science - Arizona State', 'Bachelor of Science in Computer Science - University of California', 'Master - Faculdade de Engenharia da Universidade do Porto', 'Master of Engineering in Computing - Imperial College', 'Master - Moscow State University', 'Bachelor of Engineering in Computer Engineering - Mumbai University', 'Bachelor of Science in Computer Science - University of colorado', 'Bachelor of Science in Computer Science - Universidade Catolica', 'Master of Science in Computer Science - University of California']
recommendations['88'] = ['Online Course - Mongodb University', 'Bachelor of Science in Computer Science - Purdue University', 'Bachelor - Universidade de Sao Paulo', 'Certificate - Nova Scotia Community College', 'Bachelor of Science in Computer Science - University of Texas', 'Bachelor of Science in Computer Science - California State University', 'Bachelor of Science in Computer Science - University of California', 'Bachelor Computer Science - Central University', 'Bachelor of Science in Computer Science - Florida State', 'Certificate - British Columbia Institute of Technology']
recommendations['89'] = ['Computer Science - University of California', 'Bachelor of Science in Computer Science - University of California', 'Bachelor of Science in Computer Science - University of Maryland', 'Certificate - Nova Scotia Community College', 'Bachelor of Engineering in - Gujarat Technological University', 'Bachelor of Engineering in Computer Science - Anna University', 'Master of Science in Computer Science - Maharishi University of Management', 'Bachelor of Science in Computer Science - Instituto Superior Tecnico', 'Bachelor of Science in Computer Science - University of Michigan', 'Bachelor of Engineering in - Anna University']
recommendations['90'] = ['Bachelor of Science in Computer Science - Central University ', 'Bachelor of Science in Computer Science - University of California', 'Bachelor of Science in Computer Science - University of the Philippines', 'Bachelor information Technology - Rochester Institute of Technology', 'Bachelor of Engineering in Computer Science - Anna University', 'Master of Science in Computer Science - University of Illinois', 'Bachelor Computer Science - Universita Degli Studi di Padova', 'Bachelor of Science in Computer Science - University of Illinois', 'Master of Science in Computer Science - Northwestern University', 'Bachelor Technology - Jawaharlal Nehru Technological University']
recommendations['91'] = ['Bachelor of Science in Computer Science - University of California', 'Master of Science in Computer Science - Technical University', 'Computer Science - University of Waterloo', 'Bachelor of Science in Computer Science - Brigham Young University', 'Bachelor of Science - University of Toronto', 'Bachelor of Science in Computer Science - Wentworth institute of Technology', 'Bachelor of Science in Computer Science - Universidade Catolica', 'Full Stack Web Development - Code Camp', 'Bachelor of Science in Computer Science - University of Washington', 'Bachelor of Information Technology in Systems Engineering - Hasso Plattner Institute']

$('.dropdown-menu a').on('click', function(){

    $('.dropdown-toggle').html($(this).html() + ' <span class="caret"></span>');
    
    $("#user_based tbody tr").remove();

    var subcategory_id = $(this).attr('data-value');
    var recommended_courses = recommendations[subcategory_id]
    var course;
    for( course in recommended_courses) {
        $('#user_based tbody').append('<tr><td>' + recommended_courses[course] + '</td></tr>');
    }
	
    //var user_based_reco = document.getElementById('user_based').rows;
    //console.log(user_based_reco.length);
    //document.getElementById('item_based').deleteRow(0)
    //$('#item_based tr:last').after('<tr><td>1</td></tr>');
});
